// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: route.proto

package emergency_response

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EvacuationRouteService_Create_FullMethodName  = "/emergency_response.EvacuationRouteService/Create"
	EvacuationRouteService_GetById_FullMethodName = "/emergency_response.EvacuationRouteService/GetById"
	EvacuationRouteService_GetAll_FullMethodName  = "/emergency_response.EvacuationRouteService/GetAll"
	EvacuationRouteService_Update_FullMethodName  = "/emergency_response.EvacuationRouteService/Update"
	EvacuationRouteService_Delete_FullMethodName  = "/emergency_response.EvacuationRouteService/Delete"
)

// EvacuationRouteServiceClient is the client API for EvacuationRouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EvacuationRouteServiceClient interface {
	Create(ctx context.Context, in *RoutesCreateReq, opts ...grpc.CallOption) (*RoutesRes, error)
	GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*RoutesGetByIdRes, error)
	GetAll(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*RoutesGetAllRes, error)
	Update(ctx context.Context, in *RoutesUpdateReq, opts ...grpc.CallOption) (*RoutesRes, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
}

type evacuationRouteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEvacuationRouteServiceClient(cc grpc.ClientConnInterface) EvacuationRouteServiceClient {
	return &evacuationRouteServiceClient{cc}
}

func (c *evacuationRouteServiceClient) Create(ctx context.Context, in *RoutesCreateReq, opts ...grpc.CallOption) (*RoutesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesRes)
	err := c.cc.Invoke(ctx, EvacuationRouteService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evacuationRouteServiceClient) GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*RoutesGetByIdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesGetByIdRes)
	err := c.cc.Invoke(ctx, EvacuationRouteService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evacuationRouteServiceClient) GetAll(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*RoutesGetAllRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesGetAllRes)
	err := c.cc.Invoke(ctx, EvacuationRouteService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evacuationRouteServiceClient) Update(ctx context.Context, in *RoutesUpdateReq, opts ...grpc.CallOption) (*RoutesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesRes)
	err := c.cc.Invoke(ctx, EvacuationRouteService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evacuationRouteServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, EvacuationRouteService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvacuationRouteServiceServer is the server API for EvacuationRouteService service.
// All implementations must embed UnimplementedEvacuationRouteServiceServer
// for forward compatibility
type EvacuationRouteServiceServer interface {
	Create(context.Context, *RoutesCreateReq) (*RoutesRes, error)
	GetById(context.Context, *ById) (*RoutesGetByIdRes, error)
	GetAll(context.Context, *Filter) (*RoutesGetAllRes, error)
	Update(context.Context, *RoutesUpdateReq) (*RoutesRes, error)
	Delete(context.Context, *ById) (*Void, error)
	mustEmbedUnimplementedEvacuationRouteServiceServer()
}

// UnimplementedEvacuationRouteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEvacuationRouteServiceServer struct {
}

func (UnimplementedEvacuationRouteServiceServer) Create(context.Context, *RoutesCreateReq) (*RoutesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEvacuationRouteServiceServer) GetById(context.Context, *ById) (*RoutesGetByIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedEvacuationRouteServiceServer) GetAll(context.Context, *Filter) (*RoutesGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedEvacuationRouteServiceServer) Update(context.Context, *RoutesUpdateReq) (*RoutesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEvacuationRouteServiceServer) Delete(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEvacuationRouteServiceServer) mustEmbedUnimplementedEvacuationRouteServiceServer() {
}

// UnsafeEvacuationRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvacuationRouteServiceServer will
// result in compilation errors.
type UnsafeEvacuationRouteServiceServer interface {
	mustEmbedUnimplementedEvacuationRouteServiceServer()
}

func RegisterEvacuationRouteServiceServer(s grpc.ServiceRegistrar, srv EvacuationRouteServiceServer) {
	s.RegisterService(&EvacuationRouteService_ServiceDesc, srv)
}

func _EvacuationRouteService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutesCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvacuationRouteServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvacuationRouteService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvacuationRouteServiceServer).Create(ctx, req.(*RoutesCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvacuationRouteService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvacuationRouteServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvacuationRouteService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvacuationRouteServiceServer).GetById(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvacuationRouteService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvacuationRouteServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvacuationRouteService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvacuationRouteServiceServer).GetAll(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvacuationRouteService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutesUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvacuationRouteServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvacuationRouteService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvacuationRouteServiceServer).Update(ctx, req.(*RoutesUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvacuationRouteService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvacuationRouteServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvacuationRouteService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvacuationRouteServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

// EvacuationRouteService_ServiceDesc is the grpc.ServiceDesc for EvacuationRouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EvacuationRouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emergency_response.EvacuationRouteService",
	HandlerType: (*EvacuationRouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EvacuationRouteService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _EvacuationRouteService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _EvacuationRouteService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EvacuationRouteService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EvacuationRouteService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "route.proto",
}
