// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: resource.proto

package emergency_response

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EmergencyResourceService_Create_FullMethodName  = "/emergency_response.EmergencyResourceService/Create"
	EmergencyResourceService_GetById_FullMethodName = "/emergency_response.EmergencyResourceService/GetById"
	EmergencyResourceService_GetAll_FullMethodName  = "/emergency_response.EmergencyResourceService/GetAll"
	EmergencyResourceService_Update_FullMethodName  = "/emergency_response.EmergencyResourceService/Update"
	EmergencyResourceService_Delete_FullMethodName  = "/emergency_response.EmergencyResourceService/Delete"
)

// EmergencyResourceServiceClient is the client API for EmergencyResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmergencyResourceServiceClient interface {
	Create(ctx context.Context, in *ResourcesCreateReq, opts ...grpc.CallOption) (*ResourcesRes, error)
	GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*ResourcesGetByIdRes, error)
	GetAll(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ResourcesGetAllRes, error)
	Update(ctx context.Context, in *ResourcesUpdateReq, opts ...grpc.CallOption) (*ResourcesRes, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
}

type emergencyResourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmergencyResourceServiceClient(cc grpc.ClientConnInterface) EmergencyResourceServiceClient {
	return &emergencyResourceServiceClient{cc}
}

func (c *emergencyResourceServiceClient) Create(ctx context.Context, in *ResourcesCreateReq, opts ...grpc.CallOption) (*ResourcesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesRes)
	err := c.cc.Invoke(ctx, EmergencyResourceService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emergencyResourceServiceClient) GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*ResourcesGetByIdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesGetByIdRes)
	err := c.cc.Invoke(ctx, EmergencyResourceService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emergencyResourceServiceClient) GetAll(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ResourcesGetAllRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesGetAllRes)
	err := c.cc.Invoke(ctx, EmergencyResourceService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emergencyResourceServiceClient) Update(ctx context.Context, in *ResourcesUpdateReq, opts ...grpc.CallOption) (*ResourcesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesRes)
	err := c.cc.Invoke(ctx, EmergencyResourceService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emergencyResourceServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, EmergencyResourceService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmergencyResourceServiceServer is the server API for EmergencyResourceService service.
// All implementations must embed UnimplementedEmergencyResourceServiceServer
// for forward compatibility
type EmergencyResourceServiceServer interface {
	Create(context.Context, *ResourcesCreateReq) (*ResourcesRes, error)
	GetById(context.Context, *ById) (*ResourcesGetByIdRes, error)
	GetAll(context.Context, *Filter) (*ResourcesGetAllRes, error)
	Update(context.Context, *ResourcesUpdateReq) (*ResourcesRes, error)
	Delete(context.Context, *ById) (*Void, error)
	mustEmbedUnimplementedEmergencyResourceServiceServer()
}

// UnimplementedEmergencyResourceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmergencyResourceServiceServer struct {
}

func (UnimplementedEmergencyResourceServiceServer) Create(context.Context, *ResourcesCreateReq) (*ResourcesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEmergencyResourceServiceServer) GetById(context.Context, *ById) (*ResourcesGetByIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedEmergencyResourceServiceServer) GetAll(context.Context, *Filter) (*ResourcesGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedEmergencyResourceServiceServer) Update(context.Context, *ResourcesUpdateReq) (*ResourcesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEmergencyResourceServiceServer) Delete(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEmergencyResourceServiceServer) mustEmbedUnimplementedEmergencyResourceServiceServer() {
}

// UnsafeEmergencyResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmergencyResourceServiceServer will
// result in compilation errors.
type UnsafeEmergencyResourceServiceServer interface {
	mustEmbedUnimplementedEmergencyResourceServiceServer()
}

func RegisterEmergencyResourceServiceServer(s grpc.ServiceRegistrar, srv EmergencyResourceServiceServer) {
	s.RegisterService(&EmergencyResourceService_ServiceDesc, srv)
}

func _EmergencyResourceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmergencyResourceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmergencyResourceService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmergencyResourceServiceServer).Create(ctx, req.(*ResourcesCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmergencyResourceService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmergencyResourceServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmergencyResourceService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmergencyResourceServiceServer).GetById(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmergencyResourceService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmergencyResourceServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmergencyResourceService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmergencyResourceServiceServer).GetAll(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmergencyResourceService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmergencyResourceServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmergencyResourceService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmergencyResourceServiceServer).Update(ctx, req.(*ResourcesUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmergencyResourceService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmergencyResourceServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmergencyResourceService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmergencyResourceServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

// EmergencyResourceService_ServiceDesc is the grpc.ServiceDesc for EmergencyResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmergencyResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emergency_response.EmergencyResourceService",
	HandlerType: (*EmergencyResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EmergencyResourceService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _EmergencyResourceService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _EmergencyResourceService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EmergencyResourceService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EmergencyResourceService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource.proto",
}
